Try shellcheck linter

diff --git a/autobackupdb b/autobackupdb
--- a/autobackupdb
+++ b/autobackupdb
@@ -1,17 +1,9 @@
 #!/bin/bash
 
 BACKUP_DIR="/var/autobackupdb"
-GZIP="-9"
 
 shopt -s nullglob
 set -o pipefail
-
-export GZIP
-cd "${BACKUP_DIR}"
-if [ $? -ne 0 ]; then
-	printf "Error: could not chdir to '%s'\n" "${BACKUP_DIR}"
-	exit 1
-fi
 
 function backup_dpkg_list {
 	dpkg -l > "${BACKUP_DIR}/dpkg.list"
@@ -32,7 +24,8 @@ function backup_pg {
 		printf "* Dumping pgsql '%s'... " "${DBNAME}"
 		(
 			set -e
-			local TMPDB=`mktemp "${BACKUP_DIR}/tmp.${DBNAME}.XXXXXX"`
+			local TMPDB
+			TMPDB=$(mktemp "${BACKUP_DIR}/tmp.${DBNAME}.XXXXXX")
 			su postgres -c "pg_dump -Fc \"${DBNAME}\"" > "${TMPDB}"
 			mv "${TMPDB}" "${BACKUP_DIR}/pgsql.${DBNAME}.pg_dump.Fc"
 		)
@@ -65,7 +58,8 @@ function backup_mysql {
 		printf "* Dumping mysql '%s'... " "${DBNAME}"
 		(
 			set -e
-			local TMPDB=`mktemp "${BACKUP_DIR}/tmp.${DBNAME}.XXXXXX"`
+			local TMPDB
+			TMPDB=$(mktemp "${BACKUP_DIR}/tmp.${DBNAME}.XXXXXX")
 			mysqldump "${DBNAME}" | gzip > "${TMPDB}"
 			mv "${TMPDB}" "${BACKUP_DIR}/mysql.${DBNAME}.dump.gz"
 		)
@@ -84,7 +78,8 @@ function backup_mongo {
 	if [ $? -ne 0 ]; then
 		return 0
 	fi
-	local DB_LIST=( $(mongo --quiet --eval  "printjson(db.adminCommand('listDatabases'))" | php -r '$r=json_decode(file_get_contents("php://stdin"),true);foreach($r["databases"]as$d){printf("%s\n",$d["name"]);};') )
+	local DB_LIST
+	DB_LIST=( $(mongo --quiet --eval  "printjson(db.adminCommand('listDatabases'))" | php -r '$r=json_decode(file_get_contents("php://stdin"),true);foreach($r["databases"]as$d){printf("%s\n",$d["name"]);};') )
 	if [ $? -ne 0 ]; then
 		printf "Error: could not list Mongo's databases!\n"
 		return 1
@@ -94,7 +89,8 @@ function backup_mongo {
 		printf "* Dumping mongo '%s'... " "${DBNAME}"
 		(
 			set -e
-			local TMPDB=$(mktemp -d "${BACKUP_DIR}/mongo.${DBNAME}.db.XXXXXX")
+			local TMPDB
+			TMPDB=$(mktemp -d "${BACKUP_DIR}/mongo.${DBNAME}.db.XXXXXX")
 			mongodump -o "${TMPDB}" -d "${DBNAME}"
 			rm -Rf "${BACKUP_DIR}/mongo.$DBNAME.db"
 			mv "${TMPDB}" "${BACKUP_DIR}/mongo.${DBNAME}.db"
@@ -111,6 +107,13 @@ function backup_mongo {
 
 function main {
 	local RET=0
+
+	cd "${BACKUP_DIR}"
+	if [ $? -ne 0 ]; then
+		printf "Error: could not chdir to '%s'\n" "${BACKUP_DIR}"
+		return 1
+	fi
+
 
 	backup_dpkg_list
 	(( RET = RET || $? ))
@@ -131,3 +134,5 @@ function main {
 }
 
 main "$@"
+
+# shellcheck disable=SC2016
